-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  type text NOT NULL DEFAULT 'note'::text CHECK (type = ANY (ARRAY['call'::text, 'email'::text, 'visit'::text, 'whatsapp'::text, 'meeting'::text, 'note'::text, 'task'::text, 'stage_change'::text])),
  title text NOT NULL,
  description text,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.app_permissions (
  code text NOT NULL,
  name text NOT NULL,
  module text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_permissions_pkey PRIMARY KEY (code)
);
CREATE TABLE public.app_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  is_system boolean DEFAULT false,
  color text DEFAULT 'bg-slate-100 text-slate-800'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.assignment_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assignment_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  CONSTRAINT assignment_items_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_items_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.sample_assignments(id),
  CONSTRAINT assignment_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  operation text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  organization_id uuid NOT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bank_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  min_stock_alert integer DEFAULT 10,
  CONSTRAINT bank_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT bank_inventory_bank_id_fkey FOREIGN KEY (bank_id) REFERENCES public.sample_banks(id),
  CONSTRAINT bank_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.billing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  tier text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  features jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  interval text DEFAULT 'month'::text,
  provider_price_id text,
  paypal_plan_id text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_prices_pkey PRIMARY KEY (id),
  CONSTRAINT billing_prices_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.billing_plans(id)
);
CREATE TABLE public.billing_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  subscription_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  status text NOT NULL,
  provider text NOT NULL,
  provider_transaction_id text,
  payment_method_type text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT billing_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.commercial_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  title text NOT NULL,
  min_quantity integer NOT NULL DEFAULT 1,
  bonus_quantity integer DEFAULT 0,
  discount_percentage numeric DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commercial_offers_pkey PRIMARY KEY (id),
  CONSTRAINT commercial_offers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.compensation_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  base_salary numeric DEFAULT 100.00,
  food_stamps numeric DEFAULT 100.00,
  vehicle_support numeric DEFAULT 200.00,
  sales_threshold integer DEFAULT 2000,
  commission_rate numeric DEFAULT 0.015,
  papeleta_conversion_factor integer DEFAULT 6,
  daily_no_stay_amount numeric DEFAULT 30.00,
  daily_with_stay_amount numeric DEFAULT 65.00,
  fuel_autonomy_factor numeric DEFAULT 6.00,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT compensation_policies_pkey PRIMARY KEY (id),
  CONSTRAINT compensation_policies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.contact_health_centers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid NOT NULL,
  health_center_id uuid NOT NULL,
  schedule text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT contact_health_centers_pkey PRIMARY KEY (id),
  CONSTRAINT contact_health_centers_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT contact_health_centers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contact_health_centers_health_center_id_fkey FOREIGN KEY (health_center_id) REFERENCES public.health_centers(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  contact_type USER-DEFINED NOT NULL,
  specialty text,
  address text,
  city text,
  phone text,
  email text,
  work_hours text,
  priority USER-DEFINED DEFAULT 'medium'::priority_level,
  notes text,
  latitude numeric,
  longitude numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  zone_id uuid,
  state text,
  region text,
  organization_id uuid,
  visit_count integer DEFAULT 0,
  last_visit date,
  rif text,
  owner_name text,
  sanitary_permits boolean DEFAULT false,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT contacts_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text DEFAULT 'open'::text,
  goals_json jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT cycles_pkey PRIMARY KEY (id),
  CONSTRAINT cycles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.daily_plan_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  weekly_plan_id uuid NOT NULL,
  day_of_week text NOT NULL,
  date date NOT NULL,
  directory_item_id uuid NOT NULL,
  turn text DEFAULT 'AM'::text,
  visit_order integer DEFAULT 0,
  status text DEFAULT 'planned'::text,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT daily_plan_details_pkey PRIMARY KEY (id),
  CONSTRAINT daily_plan_details_weekly_plan_id_fkey FOREIGN KEY (weekly_plan_id) REFERENCES public.weekly_plans(id),
  CONSTRAINT daily_plan_details_directory_item_id_fkey FOREIGN KEY (directory_item_id) REFERENCES public.directory_items(id),
  CONSTRAINT daily_plan_details_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.daily_plan_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid,
  user_id uuid NOT NULL,
  visit_id uuid,
  contact_id uuid,
  title text NOT NULL,
  description text,
  scheduled_time time without time zone,
  duration_minutes integer DEFAULT 30,
  priority integer DEFAULT 0,
  status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT daily_plan_items_pkey PRIMARY KEY (id),
  CONSTRAINT daily_plan_items_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT daily_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.daily_plans(id),
  CONSTRAINT daily_plan_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.daily_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_date date NOT NULL,
  title text,
  notes text,
  priority text DEFAULT 'normal'::text,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT daily_plans_pkey PRIMARY KEY (id),
  CONSTRAINT daily_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.deals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  zone_id uuid,
  contact_id uuid,
  title text NOT NULL,
  value numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  stage text NOT NULL DEFAULT 'prospecting'::text CHECK (stage = ANY (ARRAY['prospecting'::text, 'contacted'::text, 'proposal'::text, 'negotiation'::text, 'won'::text, 'lost'::text])),
  probability integer DEFAULT 10 CHECK (probability >= 0 AND probability <= 100),
  expected_close_date date,
  source text DEFAULT 'other'::text CHECK (source = ANY (ARRAY['visit'::text, 'cold_call'::text, 'referral'::text, 'landing'::text, 'whatsapp'::text, 'other'::text])),
  notes text,
  lost_reason text,
  won_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.debug_auth_dump (
  id uuid,
  instance_id uuid,
  aud character varying,
  role character varying,
  email character varying,
  email_confirmed_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_user_meta_data jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  is_sso_user boolean
);
CREATE TABLE public.debug_roles_dump (
  id uuid,
  user_id uuid,
  company_id uuid,
  role text,
  permissions jsonb,
  territory text,
  supervisor_id uuid,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  zone_id uuid
);
CREATE TABLE public.debug_triggers_dump (
  event_object_schema name,
  event_object_table name,
  trigger_name name,
  action_statement character varying,
  action_timing character varying
);
CREATE TABLE public.detalle_entrega_banco (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entrega_banco_id uuid NOT NULL,
  stock_muestra_id uuid NOT NULL,
  cantidad_inicial integer NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT detalle_entrega_banco_pkey PRIMARY KEY (id),
  CONSTRAINT detalle_entrega_banco_entrega_banco_id_fkey FOREIGN KEY (entrega_banco_id) REFERENCES public.entregas_banco(id),
  CONSTRAINT detalle_entrega_banco_stock_muestra_id_fkey FOREIGN KEY (stock_muestra_id) REFERENCES public.inventario_muestras(id),
  CONSTRAINT detalle_entrega_banco_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.directory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_id uuid NOT NULL,
  entity_type text NOT NULL,
  name text NOT NULL,
  address text,
  city text,
  zone_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT directory_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispensacion_muestras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventario_banco_id uuid NOT NULL,
  fecha_dispensacion date NOT NULL,
  cantidad_dispensada integer NOT NULL,
  entregado_a text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispensacion_muestras_pkey PRIMARY KEY (id),
  CONSTRAINT dispensacion_muestras_inventario_banco_id_fkey FOREIGN KEY (inventario_banco_id) REFERENCES public.inventario_muestras(id),
  CONSTRAINT dispensacion_muestras_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.dispensacion_pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  health_center_id uuid,
  product_id uuid,
  lote text,
  fecha_vencimiento date,
  nombre_paciente text NOT NULL,
  cedula text,
  telefono text,
  diagnostico text,
  fecha_dispensacion date NOT NULL,
  cantidad_dispensada integer NOT NULL,
  dispensado_por text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispensacion_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT dispensacion_pacientes_health_center_id_fkey FOREIGN KEY (health_center_id) REFERENCES public.health_centers(id),
  CONSTRAINT dispensacion_pacientes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT dispensacion_pacientes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.distributors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  email text,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT distributors_pkey PRIMARY KEY (id),
  CONSTRAINT distributors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.doctor_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  health_center_id uuid,
  direccion text,
  zona_sector text,
  ciudad text,
  estado text,
  dias_atencion text NOT NULL,
  hora_inicio time without time zone NOT NULL,
  hora_fin time without time zone NOT NULL,
  activo boolean DEFAULT true,
  notas text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT doctor_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_schedules_health_center_id_fkey FOREIGN KEY (health_center_id) REFERENCES public.health_centers(id),
  CONSTRAINT doctor_schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT doctor_schedules_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT doctor_schedules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.doctor_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid UNIQUE,
  total_visits integer DEFAULT 0,
  visits_last_30_days integer DEFAULT 0,
  visits_last_90_days integer DEFAULT 0,
  samples_received integer DEFAULT 0,
  products_presented integer DEFAULT 0,
  avg_visit_duration_minutes numeric DEFAULT 0,
  score_value numeric DEFAULT 0,
  score_category character varying DEFAULT 'low'::character varying,
  ideal_visit_frequency_days integer DEFAULT 30,
  days_since_last_visit integer DEFAULT 0,
  visit_gap_status character varying DEFAULT 'on_track'::character varying,
  last_visit_date timestamp with time zone,
  last_calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_scores_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_scores_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.doctors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  representative_id uuid,
  name text NOT NULL,
  birth_date date,
  phone text,
  mobile text,
  email text,
  specialty text,
  msds text,
  cm text,
  address text,
  location text,
  city text,
  state text,
  health_center text,
  days text,
  start_time time without time zone,
  end_time time without time zone,
  potential text CHECK (potential = ANY (ARRAY['Alto'::text, 'Medio'::text, 'Bajo'::text])),
  observations text,
  last_visit date,
  status text DEFAULT 'Activo'::text CHECK (status = ANY (ARRAY['Activo'::text, 'Inactivo'::text])),
  instagram text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  specialty_id uuid,
  organization_id uuid,
  lat double precision,
  lng double precision,
  zone_id uuid,
  visit_count integer DEFAULT 0,
  CONSTRAINT doctors_pkey PRIMARY KEY (id),
  CONSTRAINT doctors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT doctors_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES public.profiles(id),
  CONSTRAINT doctors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT doctors_specialty_id_fkey FOREIGN KEY (specialty_id) REFERENCES public.specialties(id),
  CONSTRAINT doctors_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.drugstores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  code text,
  contact_name text,
  phone text,
  email text,
  address text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contact_id uuid,
  type text CHECK (type = ANY (ARRAY['Nacional'::text, 'Regional'::text])),
  location text,
  organization_id uuid,
  CONSTRAINT drugstores_pkey PRIMARY KEY (id),
  CONSTRAINT drugstores_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT drugstores_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT drugstores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.entrega_muestras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  stock_muestra_id uuid NOT NULL,
  doctor_id uuid,
  cantidad_entregada integer NOT NULL,
  fecha_entrega date NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entrega_muestras_pkey PRIMARY KEY (id),
  CONSTRAINT entrega_muestras_stock_muestra_id_fkey FOREIGN KEY (stock_muestra_id) REFERENCES public.inventario_muestras(id),
  CONSTRAINT entrega_muestras_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.entregas_banco (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  health_center_id uuid,
  servicio text,
  jefe_servicio text,
  fecha_entrega date NOT NULL,
  entregado_por text,
  foto_acta_url text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entregas_banco_pkey PRIMARY KEY (id),
  CONSTRAINT entregas_banco_health_center_id_fkey FOREIGN KEY (health_center_id) REFERENCES public.health_centers(id),
  CONSTRAINT entregas_banco_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid,
  title text NOT NULL,
  description text,
  event_type text DEFAULT 'presentation'::text,
  contact_id uuid,
  location text,
  scheduled_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  status text DEFAULT 'scheduled'::text,
  attendees_count integer DEFAULT 0,
  notes text,
  materials_used ARRAY,
  products_presented ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT events_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT events_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.expense_budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid,
  category text NOT NULL,
  budget_amount numeric NOT NULL,
  period_type text DEFAULT 'monthly'::text,
  period_start date NOT NULL,
  period_end date NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_budgets_pkey PRIMARY KEY (id),
  CONSTRAINT expense_budgets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.expense_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  week_start_date date NOT NULL,
  start_km integer NOT NULL,
  end_km integer NOT NULL,
  start_km_photo_url text,
  end_km_photo_url text,
  pernocta_days integer DEFAULT 0,
  no_pernocta_days integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'paid'::text])),
  total_reimbursement numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_reports_pkey PRIMARY KEY (id),
  CONSTRAINT expense_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT expense_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid,
  category text NOT NULL,
  subcategory text,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  vendor text,
  receipt_url text,
  visit_id uuid,
  status text DEFAULT 'pending'::text,
  approved_by uuid,
  approved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  zone_id uuid,
  organization_id uuid,
  start_km double precision,
  end_km double precision,
  km_start_url text,
  km_end_url text,
  custom_category text,
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT expenses_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id),
  CONSTRAINT expenses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.field_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  supervisor_id uuid NOT NULL,
  representative_id uuid NOT NULL,
  score_vademecum integer CHECK (score_vademecum >= 1 AND score_vademecum <= 5),
  score_objection_handling integer CHECK (score_objection_handling >= 1 AND score_objection_handling <= 5),
  score_closing_skills integer CHECK (score_closing_skills >= 1 AND score_closing_skills <= 5),
  score_pre_call_planning integer CHECK (score_pre_call_planning >= 1 AND score_pre_call_planning <= 5),
  score_sample_strategy boolean DEFAULT false,
  strengths text,
  areas_for_improvement text,
  action_plan text,
  evaluation_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT field_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT field_evaluations_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT field_evaluations_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.profiles(id),
  CONSTRAINT field_evaluations_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.fixed_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  assigned_to uuid,
  condition text DEFAULT 'good'::text,
  assigned_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fixed_assets_pkey PRIMARY KEY (id),
  CONSTRAINT fixed_assets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.health_centers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  facility_type text NOT NULL,
  address text,
  city text,
  state text,
  zone_id text,
  phone text,
  potential text,
  last_visit date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  lat double precision,
  lng double precision,
  visit_count integer DEFAULT 0,
  CONSTRAINT health_centers_pkey PRIMARY KEY (id),
  CONSTRAINT health_centers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT health_centers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.help_articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  category text NOT NULL,
  subcategory text,
  order_index integer DEFAULT 0,
  is_published boolean DEFAULT true,
  views_count integer DEFAULT 0,
  helpful_count integer DEFAULT 0,
  not_helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT help_articles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventario_droguerias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drogueria_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  cantidad integer NOT NULL DEFAULT 0,
  precio_venta_farmacia numeric NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventario_droguerias_pkey PRIMARY KEY (id),
  CONSTRAINT inventario_droguerias_drogueria_id_fkey FOREIGN KEY (drogueria_id) REFERENCES public.drugstores(id),
  CONSTRAINT inventario_droguerias_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id)
);
CREATE TABLE public.inventario_muestras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  lote text NOT NULL,
  fecha_fabricacion date,
  fecha_vencimiento date NOT NULL,
  cantidad_asignada integer NOT NULL DEFAULT 0 CHECK (cantidad_asignada >= 0),
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventario_muestras_pkey PRIMARY KEY (id),
  CONSTRAINT inventario_muestras_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventario_muestras_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity_change integer NOT NULL,
  movement_type text NOT NULL,
  contact_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT inventory_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_movements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['draft'::text, 'open'::text, 'paid'::text, 'void'::text, 'uncollectible'::text])),
  due_date timestamp with time zone,
  paid_at timestamp with time zone,
  invoice_number text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lista_precios_biofarco (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producto_id uuid NOT NULL UNIQUE,
  precio_base numeric NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lista_precios_biofarco_pkey PRIMARY KEY (id),
  CONSTRAINT lista_precios_biofarco_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id)
);
CREATE TABLE public.market_share_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  zone_id uuid,
  product_category text NOT NULL,
  period_date date NOT NULL,
  our_market_share numeric,
  competitor_market_share numeric,
  total_market_value numeric,
  source text DEFAULT 'Manual Audit'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT market_share_data_pkey PRIMARY KEY (id),
  CONSTRAINT market_share_data_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT market_share_data_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.master_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  master_id uuid,
  action_type text NOT NULL,
  target_id uuid,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT master_audit_logs_master_id_fkey FOREIGN KEY (master_id) REFERENCES auth.users(id)
);
CREATE TABLE public.master_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  is_active boolean DEFAULT true,
  CONSTRAINT master_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.materiales_promocionales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  tipo text,
  product_id uuid,
  cantidad_disponible integer NOT NULL DEFAULT 0,
  cantidad_inicial integer NOT NULL,
  fecha_recepcion date,
  notas text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT materiales_promocionales_pkey PRIMARY KEY (id),
  CONSTRAINT materiales_promocionales_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT materiales_promocionales_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text DEFAULT 'info'::text,
  category text DEFAULT 'system'::text,
  priority text DEFAULT 'normal'::text,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  action_label text,
  reference_type text,
  reference_id uuid,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.objectives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid,
  title text NOT NULL,
  description text,
  objective_type text DEFAULT 'monthly'::text,
  category text DEFAULT 'visits'::text,
  target_value numeric NOT NULL DEFAULT 0,
  current_value numeric DEFAULT 0,
  unit text DEFAULT 'count'::text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text DEFAULT 'active'::text,
  priority text DEFAULT 'normal'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  zone_id uuid,
  organization_id uuid,
  CONSTRAINT objectives_pkey PRIMARY KEY (id),
  CONSTRAINT objectives_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT objectives_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id),
  CONSTRAINT objectives_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  plan_tier text DEFAULT 'free'::text CHECK (plan_tier = ANY (ARRAY['free'::text, 'starter'::text, 'professional'::text, 'enterprise'::text])),
  subscription_status text DEFAULT 'trialing'::text CHECK (subscription_status = ANY (ARRAY['trialing'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'incomplete'::text])),
  stripe_customer_id text,
  stripe_subscription_id text,
  trial_ends_at timestamp with time zone DEFAULT (now() + '14 days'::interval),
  settings jsonb DEFAULT '{}'::jsonb,
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rif text,
  fiscal_address text,
  phone text,
  taxpayer_type text,
  fiscal_name text,
  is_system_owner boolean DEFAULT false,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  payment_method text NOT NULL,
  reference_number text NOT NULL,
  amount_paid numeric NOT NULL,
  proof_image_url text,
  status text DEFAULT 'pending'::text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_reports_pkey PRIMARY KEY (id),
  CONSTRAINT payment_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_payment_reports_plan FOREIGN KEY (plan_id) REFERENCES public.billing_plans(id),
  CONSTRAINT payment_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.pharmacies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  zone_id uuid,
  representative_id uuid,
  name text NOT NULL,
  rif text,
  address text,
  city text,
  sector text,
  state text,
  phone text,
  contact_phone text,
  contact_name text,
  email text,
  main_contact text,
  contact_position text,
  schedule text,
  business_hours text,
  promoted_products ARRAY,
  product_interest text,
  segmentation text,
  potential text CHECK (potential = ANY (ARRAY['Alto'::text, 'Medio'::text, 'Bajo'::text])),
  follow_up_action text,
  last_visit date,
  status text DEFAULT 'Activo'::text CHECK (status = ANY (ARRAY['Activo'::text, 'Inactivo'::text])),
  instagram text,
  notes text,
  priority text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  region text,
  organization_id uuid,
  lat double precision,
  lng double precision,
  visit_count integer DEFAULT 0,
  CONSTRAINT pharmacies_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT pharmacies_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES public.profiles(id),
  CONSTRAINT pharmacies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT pharmacies_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.pharmacy_drugstore_relations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pharmacy_id uuid,
  drugstore_id uuid,
  account_number text,
  is_preferred boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pharmacy_drugstore_relations_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_drugstore_relations_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.contacts(id),
  CONSTRAINT pharmacy_drugstore_relations_drugstore_id_fkey FOREIGN KEY (drugstore_id) REFERENCES public.drugstores(id)
);
CREATE TABLE public.pharmacy_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pharmacy_id uuid,
  title text NOT NULL,
  description text,
  status text DEFAULT 'pending'::text,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  zone_id uuid,
  organization_id uuid,
  CONSTRAINT pharmacy_reports_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_reports_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.contacts(id),
  CONSTRAINT pharmacy_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT pharmacy_reports_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id),
  CONSTRAINT pharmacy_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.pharmacy_scores (
  pharmacy_id uuid NOT NULL,
  score integer DEFAULT 0,
  level text DEFAULT 'Bronze'::text CHECK (level = ANY (ARRAY['Bronze'::text, 'Silver'::text, 'Gold'::text, 'Platinum'::text])),
  last_updated timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT pharmacy_scores_pkey PRIMARY KEY (pharmacy_id),
  CONSTRAINT pharmacy_scores_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT pharmacy_scores_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacies(id)
);
CREATE TABLE public.pharmacy_stock (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pharmacy_id uuid,
  product_id uuid,
  quantity integer DEFAULT 0,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pharmacy_stock_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_stock_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.contacts(id),
  CONSTRAINT pharmacy_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT pharmacy_stock_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pharmacy_trainings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  pharmacy_id uuid NOT NULL,
  topics ARRAY NOT NULL,
  attendees_count integer DEFAULT 1,
  evidence_photo_url text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT pharmacy_trainings_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_trainings_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT pharmacy_trainings_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.contacts(id),
  CONSTRAINT pharmacy_trainings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.pop_assignment_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid,
  material_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  CONSTRAINT pop_assignment_items_pkey PRIMARY KEY (id),
  CONSTRAINT pop_assignment_items_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.pop_assignments(id),
  CONSTRAINT pop_assignment_items_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.pop_materials(id)
);
CREATE TABLE public.pop_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid,
  representative_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'completed'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT pop_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT pop_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT pop_assignments_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES auth.users(id),
  CONSTRAINT pop_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.pop_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text DEFAULT 'General'::text,
  description text,
  image_url text,
  sku text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT pop_materials_pkey PRIMARY KEY (id),
  CONSTRAINT pop_materials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.product_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['image'::text, 'pdf'::text, 'video'::text, 'clinical_study'::text])),
  url text NOT NULL,
  title text NOT NULL,
  description text,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  CONSTRAINT product_assets_pkey PRIMARY KEY (id),
  CONSTRAINT product_assets_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT product_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT product_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.product_specialties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  specialty text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_specialties_pkey PRIMARY KEY (id),
  CONSTRAINT product_specialties_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text,
  therapeutic_area text,
  dosage text,
  presentation text,
  active_ingredients ARRAY,
  indications text,
  contraindications text,
  side_effects text,
  price numeric,
  image_url text,
  document_urls ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  product_code text UNIQUE,
  medical_specialties text,
  key_message text,
  safety_info text,
  pdf_link text,
  user_id uuid,
  organization_id uuid,
  composition text,
  clinical_evidence text,
  posology text,
  selling_points text,
  profitability_info text,
  sales_tips text,
  objection_handling text,
  sku text,
  price_cobeca numeric DEFAULT 0,
  price_dronena numeric DEFAULT 0,
  dosage_config jsonb DEFAULT '{"presentation_unit": "mL", "default_dose_mg_kg": 0, "concentration_mg_ml": 1}'::jsonb,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT products_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  employee_id text UNIQUE,
  territory text,
  phone text,
  email text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  position text,
  bio text,
  organization_id uuid,
  is_org_admin boolean DEFAULT false,
  state text,
  region text,
  invitation_status text DEFAULT 'pending'::text,
  has_completed_onboarding boolean DEFAULT false,
  is_master boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.promotional_cycle_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cycle_id uuid,
  product_id uuid,
  target_presentations integer DEFAULT 0,
  target_samples integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotional_cycle_products_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_cycle_products_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES public.promotional_cycles(id),
  CONSTRAINT promotional_cycle_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.promotional_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'active'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  objectives text,
  target_visits integer DEFAULT 0,
  target_presentations integer DEFAULT 0,
  target_samples integer DEFAULT 0,
  current_visits integer DEFAULT 0,
  current_presentations integer DEFAULT 0,
  current_samples integer DEFAULT 0,
  company_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotional_cycles_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_cycles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.promotional_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  product_id uuid,
  file_url text,
  file_size integer,
  file_type text,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT promotional_materials_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_materials_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.quote_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  discount numeric DEFAULT 0,
  total numeric DEFAULT (((quantity)::numeric * unit_price) * ((1)::numeric - (COALESCE(discount, (0)::numeric) / (100)::numeric))),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  contact_id uuid,
  pharmacy_name text,
  total_amount numeric DEFAULT 0,
  status text DEFAULT 'draft'::text,
  valid_until date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT quotes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT quotes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.registro_pvp_farmacia (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  producto_id uuid NOT NULL,
  tiene_stock boolean DEFAULT true,
  pvp numeric,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  cantidad_actual integer DEFAULT 0,
  cantidad_anterior integer DEFAULT 0,
  ventas_estimadas integer DEFAULT 0,
  pharmacy_id uuid,
  faces numeric DEFAULT 0,
  CONSTRAINT registro_pvp_farmacia_pkey PRIMARY KEY (id),
  CONSTRAINT registro_pvp_farmacia_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id),
  CONSTRAINT registro_pvp_farmacia_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacies(id)
);
CREATE TABLE public.rep_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT rep_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT rep_inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT rep_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.rep_stats_summary (
  user_id uuid NOT NULL,
  total_sales numeric DEFAULT 0,
  total_visits integer DEFAULT 0,
  total_orders integer DEFAULT 0,
  effectiveness numeric DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rep_stats_summary_pkey PRIMARY KEY (user_id),
  CONSTRAINT rep_stats_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reposiciones_banco (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  detalle_entrega_id uuid NOT NULL,
  stock_muestra_id uuid NOT NULL,
  cantidad_repuesta integer NOT NULL,
  fecha_reposicion date NOT NULL,
  usuario_reposicion text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reposiciones_banco_pkey PRIMARY KEY (id),
  CONSTRAINT reposiciones_banco_detalle_entrega_id_fkey FOREIGN KEY (detalle_entrega_id) REFERENCES public.detalle_entrega_banco(id),
  CONSTRAINT reposiciones_banco_stock_muestra_id_fkey FOREIGN KEY (stock_muestra_id) REFERENCES public.inventario_muestras(id),
  CONSTRAINT reposiciones_banco_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.role_permissions (
  role_slug text NOT NULL,
  permission_code text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_slug, permission_code),
  CONSTRAINT role_permissions_role_slug_fkey FOREIGN KEY (role_slug) REFERENCES public.app_roles(slug),
  CONSTRAINT role_permissions_permission_code_fkey FOREIGN KEY (permission_code) REFERENCES public.app_permissions(code)
);
CREATE TABLE public.sales_guides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  entity_target text NOT NULL CHECK (entity_target = ANY (ARRAY['doctor'::text, 'farmacia'::text, 'both'::text])),
  question_type text CHECK (question_type = ANY (ARRAY['situation'::text, 'problem'::text, 'implication'::text, 'need_payoff'::text])),
  question_text text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_guides_pkey PRIMARY KEY (id),
  CONSTRAINT sales_guides_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.sample_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  representative_id uuid NOT NULL,
  created_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  notes text,
  organization_id uuid,
  CONSTRAINT sample_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT sample_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sample_assignments_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES auth.users(id),
  CONSTRAINT sample_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sample_banks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  health_center_id uuid,
  responsible_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  service_name text,
  last_audit_date timestamp with time zone,
  CONSTRAINT sample_banks_pkey PRIMARY KEY (id),
  CONSTRAINT sample_banks_health_center_id_fkey FOREIGN KEY (health_center_id) REFERENCES public.health_centers(id),
  CONSTRAINT sample_banks_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sample_distributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  inventory_id uuid,
  visit_id uuid,
  contact_id uuid,
  quantity integer NOT NULL,
  distribution_date timestamp with time zone DEFAULT now(),
  notes text,
  signature_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sample_distributions_pkey PRIMARY KEY (id),
  CONSTRAINT sample_distributions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT sample_distributions_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.sample_inventory(id)
);
CREATE TABLE public.sample_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid,
  product_id uuid,
  batch_number text NOT NULL,
  lot_number text,
  quantity_total integer NOT NULL DEFAULT 0 CHECK (quantity_total >= 0),
  quantity_available integer NOT NULL DEFAULT 0 CHECK (quantity_available >= 0),
  quantity_distributed integer DEFAULT 0,
  quantity_expired integer DEFAULT 0,
  expiry_date date NOT NULL,
  received_date date DEFAULT CURRENT_DATE,
  storage_location text,
  temperature_requirements text,
  notes text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sample_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT sample_inventory_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT sample_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.sample_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity <> 0),
  movement_type USER-DEFINED NOT NULL,
  visit_id uuid,
  event_id uuid,
  bank_id uuid,
  request_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  signature_url text,
  batch_number text,
  CONSTRAINT sample_movements_pkey PRIMARY KEY (id),
  CONSTRAINT sample_movements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT sample_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sample_movements_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT sample_movements_bank_id_fkey FOREIGN KEY (bank_id) REFERENCES public.sample_banks(id),
  CONSTRAINT sample_movements_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.sample_requests(id)
);
CREATE TABLE public.sample_request_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity_requested integer NOT NULL CHECK (quantity_requested > 0),
  quantity_approved integer CHECK (quantity_approved >= 0),
  CONSTRAINT sample_request_items_pkey PRIMARY KEY (id),
  CONSTRAINT sample_request_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.sample_requests(id),
  CONSTRAINT sample_request_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.sample_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requester_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'in_transit'::text, 'delivered'::text])),
  requested_date timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_date timestamp with time zone,
  notes text,
  delivery_method text CHECK (delivery_method = ANY (ARRAY['direct'::text, 'courier'::text])),
  tracking_number text,
  organization_id uuid,
  CONSTRAINT sample_requests_pkey PRIMARY KEY (id),
  CONSTRAINT sample_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES auth.users(id),
  CONSTRAINT fk_sample_requests_requester FOREIGN KEY (requester_id) REFERENCES public.profiles(id),
  CONSTRAINT sample_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.samples (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  batch_number text NOT NULL,
  expiry_date date NOT NULL,
  quantity_available integer NOT NULL DEFAULT 0,
  quantity_distributed integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT samples_pkey PRIMARY KEY (id),
  CONSTRAINT samples_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.security_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  alert_type text NOT NULL,
  table_name text,
  description text NOT NULL,
  severity text DEFAULT 'high'::text,
  is_resolved boolean DEFAULT false,
  ai_safe_check boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT security_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_by uuid,
  CONSTRAINT site_settings_pkey PRIMARY KEY (key),
  CONSTRAINT site_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.specialties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  detail text,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT specialties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  price numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  interval text DEFAULT 'month'::text CHECK ("interval" = ANY (ARRAY['month'::text, 'year'::text])),
  features jsonb DEFAULT '[]'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  slug text,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid UNIQUE,
  plan_name text NOT NULL CHECK (plan_name = ANY (ARRAY['Free'::text, 'Starter'::text, 'Pro'::text, 'Enterprise'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  current_period_start timestamp with time zone DEFAULT timezone('utc'::text, now()),
  current_period_end timestamp with time zone,
  price_id text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  payment_method text,
  last_payment_reference text,
  is_manual boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  plan_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.billing_plans(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  subject text NOT NULL,
  description text,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  category text DEFAULT 'general'::text,
  assigned_to uuid,
  resolution text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  resolved_at timestamp with time zone,
  attachment_url text,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.system_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'success'::text])),
  is_global boolean DEFAULT false,
  active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_by uuid,
  CONSTRAINT system_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT system_alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT system_alerts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.system_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity text,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT system_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT system_audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT system_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.system_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['technical'::text, 'manual'::text, 'sop'::text, 'policy'::text])),
  content text NOT NULL,
  version text DEFAULT '1.0.0'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transfer_order_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transfer_order_id uuid,
  user_id uuid,
  action text NOT NULL,
  previous_data jsonb,
  new_data jsonb,
  changes_description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transfer_order_history_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_order_history_transfer_order_id_fkey FOREIGN KEY (transfer_order_id) REFERENCES public.transfer_orders(id),
  CONSTRAINT transfer_order_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.transfer_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transfer_order_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  bonus_units integer DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transfer_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_order_items_transfer_order_id_fkey FOREIGN KEY (transfer_order_id) REFERENCES public.transfer_orders(id),
  CONSTRAINT transfer_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.transfer_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  contact_id uuid,
  pharmacy_name text NOT NULL,
  pharmacy_address text,
  pharmacy_phone text,
  drugstore_id uuid,
  drugstore_name text NOT NULL,
  drugstore_code text,
  order_number text,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  delivery_date date,
  products jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total numeric DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'confirmed_by_distributor'::text, 'rejected_by_distributor'::text, 'delivered'::text, 'cancelled'::text])),
  notes text,
  internal_notes text,
  document_generated boolean DEFAULT false,
  document_url text,
  sent_to_email text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  zone_id uuid,
  drogueria_final_id uuid,
  codigo_pedido_externo text,
  notas_telemarketing text,
  confirmed_at timestamp with time zone,
  items_snapshot jsonb,
  organization_id uuid,
  order_type USER-DEFINED DEFAULT 'transfer'::transfer_order_type,
  CONSTRAINT transfer_orders_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT transfer_orders_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT transfer_orders_drugstore_id_fkey FOREIGN KEY (drugstore_id) REFERENCES public.drugstores(id),
  CONSTRAINT transfer_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT transfer_orders_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id),
  CONSTRAINT transfer_orders_drogueria_final_id_fkey FOREIGN KEY (drogueria_final_id) REFERENCES public.drugstores(id),
  CONSTRAINT fk_transfer_orders_user FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT user_favorites_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  company_id uuid,
  role text NOT NULL DEFAULT 'representative'::text CHECK (role = ANY (ARRAY['master'::text, 'admin'::text, 'manager'::text, 'chief'::text, 'coordinator'::text, 'supervisor'::text, 'telemarketing'::text, 'representative'::text, 'doctor'::text, 'pharmacist'::text, 'service_chief'::text, 'admin_saas'::text, 'soporte_saas'::text, 'desarrollo_saas'::text])),
  permissions jsonb DEFAULT '[]'::jsonb,
  territory text,
  supervisor_id uuid,
  is_active boolean DEFAULT true,
  zone_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  state text,
  region text,
  organization_id uuid,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_user_roles_profiles FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_roles_plain (
  user_id uuid NOT NULL,
  role text NOT NULL,
  organization_id uuid,
  zone_id uuid,
  state text,
  region text,
  supervisor_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_plain_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.user_zones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  zone_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_zones_pkey PRIMARY KEY (id),
  CONSTRAINT user_zones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_zones_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.visit_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity_presented integer DEFAULT 1,
  samples_given integer DEFAULT 0,
  material_left text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visit_products_pkey PRIMARY KEY (id),
  CONSTRAINT visit_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.visit_series (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  preferred_time time without time zone NOT NULL DEFAULT '09:00:00'::time without time zone,
  turn text CHECK (turn = ANY (ARRAY['AM'::text, 'PM'::text])),
  frequency text NOT NULL DEFAULT 'weekly'::text CHECK (frequency = ANY (ARRAY['weekly'::text, 'biweekly'::text, 'monthly'::text])),
  visit_type text,
  visit_objective text,
  notes text,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  end_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visit_series_pkey PRIMARY KEY (id),
  CONSTRAINT visit_series_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  scheduled_date timestamp with time zone,
  status text,
  user_id uuid NOT NULL,
  contact_id uuid,
  notes text,
  zone_id uuid,
  pharmacy_id uuid,
  company_id uuid,
  location_lat numeric,
  location_lng numeric,
  checkin_at timestamp with time zone,
  checkout_at timestamp with time zone,
  visit_type text,
  visit_objective text,
  visit_outcome text,
  directory_item_id uuid,
  actual_start_time timestamp with time zone,
  actual_end_time timestamp with time zone,
  arrival_time text,
  departure_time text,
  objective text,
  feedback text,
  results_notes text,
  samples_delivered text,
  products_presented ARRAY,
  products_prescribed text,
  promotional_materials text,
  contact_reaction text,
  doctor_interest text,
  emotional_state text,
  purchase_driver text,
  next_commitment text,
  next_step text,
  next_steps text,
  next_visit_date date,
  pending_followup text,
  agreements text,
  main_objection text,
  competitor_activity text,
  cycle_condition text,
  detected_purchase_reason text,
  closure_reason text,
  closure_commitment text,
  activity_performed text,
  observations_feedback text,
  key_contact boolean DEFAULT false,
  is_exception boolean DEFAULT false,
  out_of_range boolean DEFAULT false,
  representative text,
  signature_url text,
  photo_url text,
  file_url text,
  shelf_photo_url text,
  attachments ARRAY,
  geolocation text,
  check_in_latitude numeric,
  check_in_longitude numeric,
  check_out_latitude numeric,
  check_out_longitude numeric,
  distance_meters numeric,
  series_id uuid,
  interview_data jsonb,
  organization_id uuid,
  visibility_audit jsonb DEFAULT '{}'::jsonb,
  compromiso_inicio numeric DEFAULT 0,
  selling_points jsonb DEFAULT '{}'::jsonb,
  trained_staff boolean DEFAULT false,
  pop_visible boolean DEFAULT false,
  competitor_brands_detected ARRAY DEFAULT '{}'::text[],
  pop_checklist_completed jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT visits_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT visits_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.pharmacies(id),
  CONSTRAINT visits_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT visits_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id),
  CONSTRAINT visits_directory_item_id_fkey FOREIGN KEY (directory_item_id) REFERENCES public.directory_items(id),
  CONSTRAINT visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.warehouse_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  product_id uuid NOT NULL,
  batch_number text NOT NULL,
  expiry_date date NOT NULL,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  expiration_date date,
  CONSTRAINT warehouse_batches_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_batches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT warehouse_batches_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_batches_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.warehouse_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  batch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity <> 0),
  movement_type USER-DEFINED NOT NULL,
  related_request_id uuid,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT warehouse_movements_pkey PRIMARY KEY (id),
  CONSTRAINT warehouse_movements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT warehouse_movements_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT warehouse_movements_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.warehouse_batches(id),
  CONSTRAINT warehouse_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT warehouse_movements_related_request_id_fkey FOREIGN KEY (related_request_id) REFERENCES public.sample_requests(id),
  CONSTRAINT warehouse_movements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  is_main boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT warehouses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.weekly_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  cycle_id uuid NOT NULL,
  week_number integer NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text DEFAULT 'draft'::text,
  supervisor_comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_plans_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT weekly_plans_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES public.cycles(id)
);
CREATE TABLE public.work_processes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  department text,
  responsible_person text,
  objectives text,
  scope text,
  diagram_nodes jsonb DEFAULT '[]'::jsonb,
  diagram_edges jsonb DEFAULT '[]'::jsonb,
  risks jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT work_processes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  state text,
  region text,
  organization_id uuid,
  sales_threshold numeric DEFAULT 2000,
  CONSTRAINT zones_pkey PRIMARY KEY (id),
  CONSTRAINT zones_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT zones_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);