/* ========================================================================
 MASTER FRAMEWORK - EMPRESA CA
 Copyright (c) 2026 César Ascanio. Todos los derechos reservados.

 Nivel de Acceso: CONFIDENCIAL / PROPIEDAD EXCLUSIVA
 Queda estrictamente prohibida la copia, modificación, distribución,
 ingeniería inversa o uso no autorizado de este código fuente.
 ======================================================================== */

// This file is automatically generated. Do not edit it directly.
// OPTIMIZED BY SENTINEL PROTOCOL - 2026-02-23
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = "https://enmtiroqsgduhiopgtze.supabase.co";
const DEFAULT_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubXRpcm9xc2dkdWhpb3BndHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDIwMzYsImV4cCI6MjA3MTAxODAzNn0.P1iay3C7hOUE7bflU6L4dERKB59SCaKw8Lo9xL6ZTUE";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_KEY;

if (!SUPABASE_URL || !SUPABASE_URL.startsWith('https://')) {
  console.error("Supabase URL is invalid or missing protocol:", SUPABASE_URL);
}

// PERFORMANCE OPTIMIZATION: Configuración avanzada del cliente para latencia <300ms
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true, // Habilitado: permite renovación automática del JWT expirado
    detectSessionInUrl: true,
    // Estabilidad SENTINEL: Evitar colisiones en localhost
    storageKey: 'sb-medivisit-auth-token',
  },
  global: {
    headers: { 'x-application-name': 'MediVisitPro-Sentinel' },
    fetch: async (url, options) => {
      const response = await fetch(url, options);
      // Solo en desarrollo: loguear errores 401 para diagnóstico
      if (response.status === 401 && import.meta.env.DEV) {
        const text = await response.clone().text();
        console.error(`[Supabase] 401 Unauthorized on ${String(url)}`, text);
      }
      return response;
    }
  },
  db: {
    schema: 'public',
  },
});

/**
 * SENTINEL PERFORMANCE WRAPPER
 * Utilizar esta función para medir latencia en tiempo real
 */
export const fetchSentinel = async (query: any) => {
  const start = performance.now();
  const result = await query;
  const end = performance.now();
  const latency = end - start;

  if (latency > 300) {
    console.warn(`[Sentinel] Latency Warning: ${latency.toFixed(2)}ms exceed target 300ms`);
  }

  return { ...result, latency };
};
