/* ========================================================================
 MASTER FRAMEWORK - EMPRESA CA
 Copyright (c) 2026 César Ascanio. Todos los derechos reservados.

 Nivel de Acceso: CONFIDENCIAL / PROPIEDAD EXCLUSIVA
 Queda estrictamente prohibida la copia, modificación, distribución,
 ingeniería inversa o uso no autorizado de este código fuente.
 ======================================================================== */

// This file is automatically generated. Do not edit it directly.
// OPTIMIZED BY SENTINEL PROTOCOL - 2026-02-23
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_URL.startsWith('https://')) {
  console.error("Supabase URL is invalid or missing protocol:", SUPABASE_URL);
}

// PERFORMANCE OPTIMIZATION: Configuración avanzada del cliente para latencia <300ms
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: { 'x-application-name': 'MediVisitPro-Sentinel' },
  },
  db: {
    schema: 'public',
  },
  // Habilitar caché local si fuera necesario o configuraciones de reintento
});

/**
 * SENTINEL PERFORMANCE WRAPPER
 * Utilizar esta función para medir latencia en tiempo real
 */
export const fetchSentinel = async (query: any) => {
  const start = performance.now();
  const result = await query;
  const end = performance.now();
  const latency = end - start;

  if (latency > 300) {
    console.warn(`[Sentinel] Latency Warning: ${latency.toFixed(2)}ms exceed target 300ms`);
  }

  return { ...result, latency };
};